config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "home#index"
resources :users, :projects, :boards, :messages, :volunteers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
	belongs_to :project
	has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :board
	belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_one :board
	has_many :volunteers
	has_many :users, through: :volunteers
	mount_uploader :photos, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :projects
  has_many :messages

  has_many :volunteers
  has_many :projects, through: :volunteers

end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar, :neighborhood])
  end

  def after_sign_in_path_for(resource)
 	 session[:id] = current_user.id
  	 user_path(resource)
  end

  def after_sign_up_path_for(resource)
	  if resource.is_a?(User)
	  	session[:id] = current_user.id
	    user_path
	  else
	    super
	  end
	end

	def after_sign_out_path_for(resource_or_scope)
    	root_path
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]


	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def show

		@projects = Project.find_by_id(params[:id])
	end

	def create
		@current_user = current_user.id

		@projects = Project.create(name: params[:project][:name], description: params[:project][:description], date: params[:project][:date], photos: params[:project][:photos], location: params[:project][:location], people: params[:project][:people], user_id: current_user, time: params[:project][:time])
		redirect_to @projects
	end

	def edit
		@projects = Project.find( params[:id])
	end


	def update
		@project = Project.find(params[:id])
		@project.update(project_params)
		
			redirect_to project_path(@project)
		
	end

	def destroy
		
		@volunteers = Volunteer.where(project_id: params[:id])
		@volunteers.each do |t|
			t.delete
		end
		@project = Project.find(params[:id]).delete
		redirect_to user_path
	end

private

	def project_params
		params.require(:project).permit(:name, :description, :date, :photo, :people, :time, :location, :user_id)
	end

	def find_project
		@project = Project.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end


	def show
	end


end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
	def new
		@vol = Volunteer.new

	end
	def create
		@user = User.find(current_user.id)
		puts @user
		@vol = Volunteer.create(volunteer_id: @user.id, project_id: params[:volunteer][:project_id]);
		@vol.save!
		puts params.inspect
		redirect_to project_path(params[:volunteer][:project_id])
		

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/home/community_page.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Community Layout</title>
</head>
<body>
<div class="container">
	<div class="row">
		
	</div>
</div>
</body>
</html>

app/views/home/index.html.erb
<div class='imgcontainer'>
	<div class='row'>
		<div class='col s2 offset-s10' id='login'>
			<%=link_to "Log In", new_user_session_path, :class => 'btn-large cyan lighten-1'%>
		</div>
		<div class='col s6 offset-s3 splash center-align'>
		<%=image_tag('transparent.png', class: 'splashLogo')%>

			<p id='splashText'>New York City is dirty. Because trash attracts trash, it is imperative to clean it up before we're drownin in trash. Why not do something about it? Our community is all about making this cities communities even better and cleaner. In a city of over 8 million people why not help each other out? So grab your family and friends and come make NYC beautiful. </p>
			<br>
			<%=link_to "Sign Up Now", new_user_registration_path, :class => 'waves-effect waves-light btn-large cyan lighten-1 center-align' %>
		</div>
	</div>
</div>
<div class='row'>
<%@projects = Project.limit(4)%>
		<%@projects.each do |t|%>
			<div class=" dynamic col s12 m6 l3 <%=t.location%>">			
						<div class="card">
			              <div class="card-image">
			             	 <%=image_tag(t.photos, height: 252)%>
			              	<span class="card-title"><%=t.name%></span>
			              </div>
			            <div class="card-content">
			              <p><%=t.description%></p>
			            </div>
			            		  
	 		        </div>
				</div>
		<%end%>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%favicon_link_tag%>
	<title>NYClean</title>
	<%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

	<% if current_user %>
		<%if current_page?(url_for(:new_project)) || !params[:id].nil? &&  current_page?(url_for(:edit_project)) %>

		<div id='projectbackground'></div>


		<%elsif !params[:id].nil? && current_page?(:controller => 'projects', :action => "show", :id => params[:id])%>	
		<div id='projectdeets'>
		<div id='showproject'></div>
		<nav class='transparent  z-depth-0'>
			<div class="nav-wrapper transparent" id='nav'>
				<a href="#" class="brand-logo"><%=image_tag('whitelogo.png')%></a>
				<a  data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
				<ul id="nav-mobile" class="right hide-on-med-and-down">
					<li><%=link_to 'Start a Project', new_project_path, class: 'waves-effect waves-yellow btn cyan lighten-1'%></li>
					<li><%=link_to 'Neighborhoods', projects_path%></li>
					<li><%=link_to 'Home', user_path(current_user)%></li>
					<li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
				</ul>
				<ul class="side-nav" id="mobile-demo">
					<li><a class = ' btn waves-effect waves-yellow btn'' href="#">Start a project</a></li>
					<li><%=link_to 'Neighborhoods', projects_path %></li>
					<li><a class='navlink' href="#">Home</a></li>
					<li><%=link_to "Logout", destroy_user_session_path, method: :delete %></li>
				</ul>
			</div>
		</nav>

		<%else%>

			<div id='backgroundimage'></div>
			<nav class='transparent z-depth-0'>
				<div class="nav-wrapper transparent" id='nav'>
					<a href="#" class="brand-logo"><%=image_tag('whitelogo.png')%></a>
					<a  data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
					<ul id="nav-mobile" class="right hide-on-med-and-down">
						<li><%= link_to 'Start a Project', new_project_path, class: 'waves-effect waves-yellow btn cyan lighten-1' %></li>
						<li><%= link_to 'Neighborhoods', projects_path %></li>
						<li><%= link_to 'Home', user_path(current_user) %></li>
						<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
					</ul>
					<ul class="side-nav" id="mobile-demo">
						<li><%= link_to 'Start a project', new_project_path, class: 'waves-effect waves-yellow btn cyan lighten-1'%></li>
						<li><%= link_to 'Neighborhoods', projects_path %></li>
						<li><%= link_to 'Home', user_path(current_user) %></li>
						<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
					</ul>
				</div>

		</nav>
		<%end%>
	<%end%>

	<% puts current_user.inspect%>
	<%= yield %>
	
</body>
</html>

app/views/projects/edit.html.erb
<div class='row'>
	<div class="col s12 m12 l12 left-align ">
		<h4 class='create'>Edit Project</h4>	


	</div>
</div>

	<div class="row">
		


		<!-- right side of page -->
		<div id='deets' class="offset-l6 col s12 l4 ">
			
			<!-- form to create a new project -->
			<%= form_for @project do |f| %><br>
			<%= f.label :Project_name %><br><br>
			<%= f.text_field :name %><br>
			<%= f.label :Project_description %><br>
			<%= f.text_field :description %><br><br>
			<%=f.label :time%><br>
			<%=f.time_field :time%><br><br>
			<%= f.label :Date %><br>
			<%= f.date_field :date %><br><br>
			<div class="file-field input-field">
       			 <div class="btn cyan lighten-1">
          			<span>Photo</span>
          			<%= f.file_field :photos %>
          		</div>
        		<input class="file-path validate" type="text"/>
        	</div><br><br>
			<%= f.label :Volunteers %>
			<%= f.number_field :people %>
			<%= f.label :neighborhood %><br>
          
            <%= f.select :location, options_for_select([['Chelsea', 'chelseany'],["Hell's Kitchen", 'midtownwestny'], ['Midtown', 'midtownny'], ['Midtown East', 'midtowneastny'], ['East Village', 'eastvillageny'], ['Lower East Side', 'lowereastsideny'], ['West Village', 'westvillageny'], ["Greenwich Village", 'greenwichvillageny'], ['SoHo', 'sohony'], ['Tribeca', 'tribecany'], ['Chinatown', 'chinatownny'], ['Financial District', 'fidiny' ], ['Upper West Side', 'upperwestsideny'], ['Morningside Heights', 'morningsideheightsny'], ['Harlem', 'harlemny'], ['East Harlem', 'eastharlemny'], ['Upper East Side', 'uppereastsideny']])%>
            <br>
			<span class='waves-effect waves-light cyan lighten-1 btn'><%= f.submit id:"projectSubmit" %></span><br><br>
			<% end %>

		<%= link_to "Back", projects_path %></button><br><br>
		</div>
	</div>

app/views/projects/index.html.erb
<div class='row top'>
	<div class="col s12 m12 l12 welcome ">
		<h3 class='welcome'>Find a Project</h3>	
</div>
<div class='row'>
	<div class='col s12 m12 l4'>
		
  	</div>
 </div>
 <div class='row'>
 <a id='dropdownbtn' class='dropdown-button btn-large cyan lighten-1' data-activates='dropdown3'>Neighborhoods</a>
	<div id='dropdown3' class="button-group filter-button-group dropdown-content">
		 <button class='drp btn transparent z-depth-0' data-filter="*">All</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".chelseany">Chelsea</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".westvillageny">West Village</button> 
		 <button class='drp btn transparent z-depth-0' data-filter=".midtownwestny">Hell's Kitchen</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".midtownny">Midtown</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".midtowneastny">Midtown East</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".eastvillageny">East Village</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".lowereastsideny">Lower East Side</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".westvillageny">West Village</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".greenwichvillageny">The Village</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".sohony">SoHo</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".tribecany">Tribeca</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".chinatownny">Chinatown</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".fidiny">FiDi</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".upperwestsideny">Upper West Side</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".morningsideheightsny">Morningside</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".harlemny">Harlem</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".eastharlemny">East Harlem</button>
		 <button class='drp btn transparent z-depth-0' data-filter=".uppereastsideny">Upper East Side</button>

		 
	</div>
</div>
	
	<div class='row' id='cards'>
        <div class="grid"
			  data-isotope='{ "itemSelector": ".grid-item", "masonry": { "columnWidth": 200 } }'>
			
			
			<%@projects = Project.all%>
		<%@projects.each do |t|%>
			<div class="grid-item <%=t.location%> dynamic col s12 m6 l3 ">			
						<div class="card">
			              <div class="card-image">
			             	 <%=image_tag(t.photos, height: 252)%>
			              	<span class="card-title"><%=t.name%></span>
			              </div>
			            <div class="card-content">
			              <p><%=t.description%></p>
			            </div>
			            <div class="card-action">
			              <%=link_to 'View', project_path(t)%>
			            </div>		  
	 		        </div>
				</div>
		<%end%>	  
  		</div>
	</div>	
		
	</div>

	<script>
$( document ).ready(function(){
  $(".button-collapse").sideNav();
   //image thing
   

	///////////////
  $('.grid').isotope({
  // options
  itemSelector: '.grid-item',
  layoutMode: 'fitRows'
});
  
  var $grid = $('.grid').isotope({
  // options
});
  $('.filter-button-group').on( 'click', 'button', function() {
    var filterValue = $(this).attr('data-filter');
    $grid.isotope({ filter: filterValue });
  });

  $(function() {

    var $container = $('#container'),
    $select = $('#filters select');

    $container.isotope({
      itemSelector: '.item'
    });

    $select.change(function() {
      var filters = $(this).val();
      ;
      $container.isotope({
        filter: filters
      });
    });

  });

})
</script>
	

app/views/projects/new.html.erb
<div class='row'>
	<div class="col s12 m12 l12 left-align ">
		<h3 class='create'>Create a Project</h3>	


	</div>
</div>

	<div class="row">
		


		<!-- right side of page -->
		<div  class="offset-l6 col s12 l4 deets">
			
			<!-- form to create a new project -->
			<%= form_for Project.new do |f| %><br>
			<%= f.label :Project_name %><br><br>
			<%= f.text_field :name %><br>
			<%= f.label :Project_description %><br>
			<%= f.text_field :description %><br><br>
			<%=f.label :time%><br>
			<%=f.time_field :time%><br><br>
			<%= f.label :Date %><br>
			<%= f.date_field :date %><br><br>
			<div class="file-field input-field">
       			 <div class="btn cyan lighten-1">
          			<span>Photo</span>
          			<%= f.file_field :photos %>
          		</div>
        		<input class="file-path validate" type="text"/>
        	</div><br><br>
			<%= f.label :Volunteers %>
			<%= f.number_field :people %>
			<%= f.label :neighborhood%><br>
          
            <%= f.select :location, options_for_select([['Chelsea', 'chelseany'],["Hell's Kitchen", 'midtownwestny'], ['Midtown', 'midtownny'], ['Midtown East', 'midtowneastny'], ['East Village', 'eastvillageny'], ['Lower East Side', 'lowereastsideny'], ['West Village', 'westvillageny'], ["Greenwich Village", 'greenwichvillageny'], ['SoHo', 'sohony'], ['Tribeca', 'tribecany'], ['Chinatown', 'chinatownny'], ['Financial District', 'fidiny' ], ['Upper West Side', 'upperwestsideny'], ['Morningside Heights', 'morningsideheightsny'], ['Harlem', 'harlemny'], ['East Harlem', 'eastharlemny'], ['Upper East Side', 'uppereastsideny']])%>
            <br>
			<span class='waves-effect waves-light cyan lighten-1 btn'><%= f.submit id:"projectSubmit" %></span><br><br>
			<% end %>

		<%= link_to "Back", projects_path %></button><br><br>
		</div>
	</div>

app/views/projects/show.html.erb
<%@user = User.find(@project.user_id)%>
<% @project = Project.find(params[:id]) %>
<% @vols = Volunteer.where(project_id: @project.id)%>
<%@vol = @vols.length%>
<%@project.people%>
<% @people = @project.people %>
<% if @vols.length == 0 %>
	<% @width = 0 %>
<%else%>
	<%@width = (@vol.to_f/@people.to_f) * 100.0  %>
<%end%>




<div class="mapPage">
	
	
	<br>
	<div class="row all">


		<!-- enables edit and destroy ONLY if user is logged in -->
		
		
		<div class='row'>
			<div class='col l6 center-align'>
				<%=image_tag(@project.photos, width: '70%')%>
				<br>
				<div id="map">MAP DIV</div>
			</div>
			<div class='col l6'>
				<h3><%=@project.name%><%=image_tag(@user.avatar, width: '10%', class: 'useravatar')%></h3><p> By: <%=@user.name%></p>
				<% if @project.user_id == current_user.id %>
					<div >
						<%= link_to "Edit", edit_project_path(@project) %> |
						<%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?" } %>
					</div>
					<%end%>
				<h5>About this project</h5>
				<p><%=@project.date.strftime("%h/%d/%Y")%></p>
				<p><%=@project.time.strftime("%I:%M%p")%></p>
				<p><%=@project.description%></p>
				<%= form_for(:volunteer, url: volunteers_path, method: :post) do |f| %>
				<%=f.hidden_field :project_id, :value => params[:id] %>
				<% if Volunteer.exists?(volunteer_id: current_user.id, project_id: @project) || @vol == @people || @project.user_id == current_user.id %>
					<%=f.submit 'Volunteer', class: 'btn-large disabled volbtn'%>
				<%else%>
				<%=f.submit "Volunteer", class: 'btn-large cyan lighten-1 volbtn' %>
				<%end%>
			<%end%>
			<br><br>
			<div class="pb center-align">
				<div class="pb-title center-align">Volunteers</div>
				<div>
					<div class="pb-frame"  >
						<div class="pb-fill" style="width:<%=@width%>%;">&nbsp;</div>
					</div>
						<span class="pb-caption"><%=@vols.length%></span>
						<span class="pb-caption-r"><%=@project.people%></span>
				</div>
				<div style="clear: both;"></div>
				<div style="margin: 2px 0 0 0; text-align: right;">

				</div>
			</div>
			</div>
			
		</div>
	


			<br>
			
			
			</div>
		

		
			
</div>
	<div class='row'>
		
	</div>

</div>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAP'] %>"
			async defer></script>
<script type="text/javascript">
				
	var lat;
	var lng;

	geoCode();

	function geoCode(){

		var location = '<%= @project.location %>';
		// axios.get('https://maps.googleapis.com/maps/api/geocode/json?', {
		// 	params:{
		// 		address: location,
		// 		key: ""
		// 	}
		// })

		$.getJSON({
			url : 'https://maps.googleapis.com/maps/api/geocode/json?',
			data : {
				sensor : false,
				address : location,
				key : '<%= ENV['MAP']%>'
			},
			success : function(data, textStatus){
				console.log(data.results[0])
			}
		})

		.then(function(response){
			console.log(response);
			//log full response
			var formattedAddress = response.results[0].formatted_address;
			var formattedAddressOutput = `${formattedAddress}`;

			var addressComponents = response.results[0].address_components;
			var addressComponentsOutput = '<ul>';
			for(var i = 0; i < addressComponents.length; i++){
				addressComponentsOutput += `${addressComponents[i].types[0]}: ${addressComponents[i].long_name}`;
			}

			lat = response.results[0].geometry.location.lat;
			lng = response.results[0].geometry.location.lng;
		}).then(function(){
			var map = new google.maps.Map(document.getElementById('map'), {
				center: {lat: lat, lng: lng},
				zoom: 15
			});
		})
		.catch(function(error){
			console.log(error);
		})

	}
			</script>

app/views/users/show.html.erb
<body>

	<div class="row top" >
		<div id="welcomeUser" class="col s12 m12 l12 left-align ">
			<h3 class='welcome'>Welcome <%=current_user.name%></h3>
			
		</div>
		
	<div class="row">
		
		<div class="button-group filter-button-group">
		  <button class='btn-large cyan lighten-1' data-filter="*">show all</button>
		  <button class='btn-large cyan lighten-1' data-filter=".yours">Your Events</button>
		  <button id='volbtn' class='btn-large cyan lighten-1' data-filter=".volunteer">Volunteering</button> 
		</div>
	</div>
	<div class='row' id='cards'>
        <div class="grid"
			  data-isotope='{ "itemSelector": ".grid-item", "masonry": { "columnWidth": 200 } }'>
			
			  
  		
		
		
	

<%@volunteer = Volunteer.where(volunteer_id: current_user.id)%>
<%puts @volunteer.inspect%>

<%@volunteer.each do |t|%>
	<%@project = Project.where(id: t.project)%>
	<%@project.each do |t|%>
		<div class="grid-item volunteer col s12 m6 l3  dynamic">			
					<div class="card">
		              <div class="card-image">
		             	 <%=image_tag(t.photos, height: 252)%>
		              <span class="card-title"><%=t.name%></span>
		              </div>
		            <div class="card-content">
		              <p><%=t.description%></p>
		            </div>
		            <div class="card-action">
		              <%=link_to 'View',project_path(t)%>
		            </div>		  
 		        </div>
			</div>
	<%end%>
	<%end%>
<%@yours = Project.where(user_id: current_user.id)%>
	<%@yours.each do |t|%>
		<div class="grid-item yours col s12 m6 l3 dynamic">			
					<div class="card">
		              <div class="card-image">
		             	 <%=image_tag(t.photos, height: 252)%>
		              <span class="card-title"><%=t.name%></span>
		              </div>
		            <div class="card-content">
		              <p><%=t.description%></p>
		            </div>
		            <div class="card-action">
		              <%=link_to 'View',project_path(t)%>
		            </div>		  
 		        </div>
			</div>
	<%end%>

</div>
</div>


<script>
$( document ).ready(function(){
  $(".button-collapse").sideNav();
   //image thing
   

	///////////////
  $('.grid').isotope({
  // options
  itemSelector: '.grid-item',
  layoutMode: 'fitRows'
});
  
  var $grid = $('.grid').isotope({
  // options
});
  $('.filter-button-group').on( 'click', 'button', function() {
    var filterValue = $(this).attr('data-filter');
    $grid.isotope({ filter: filterValue });
  });

  $(function() {

    var $container = $('#container'),
    $select = $('#filters select');

    $container.isotope({
      itemSelector: '.item'
    });

    $select.change(function() {
      var filters = $(this).val();
      ;
      $container.isotope({
        filter: filters
      });
    });

  });

})
</script>